<a href="https://colab.research.google.com/github/BekmurodQadamboyev/Bekmurod/blob/main/copy__shape__reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1-masala

Massiv yarat: [1, 2, 3, 4] va uning shape qiymatini chiqar.

In [ ]:
import numpy as np

2-masala

np.array([[1,2,3],[4,5,6]]) massivining o‘lchamini (shape) top.

In [ ]:
arr = np.array

3-masala

np.arange(10) massivini yarat va uning shape ni aniqlang.

In [ ]:
arr = np.arange(10)
print(arr)
print(arr.shape)

4-masala

1D massivni ([1,2,3,4,5,6]) 2x3 shaklga (reshape) o‘zgartir.

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2x3 = arr_1d.reshape(2, 3)
print(arr_2x3)

5-masala

np.arange(8) massivini 4x2 shaklga o‘zgartir.

In [ ]:
arr = np.arange(8)
arr_4x2 = arr.reshape(4, 2)
print(arr_4x2)

6-masala

2x3 massivni 1D massivga (reshape) qaytar.

In [ ]:
arr_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d_from_2x3 = arr_2x3.reshape(-1)
print(arr_1d_from_2x3)

7-masala

Massivdan nusxa (copy) ol va asl massivni o‘zgartirganda nusxa o‘zgarmasligini tekshir.

8-masala

np.array([10,20,30]) dan copy yarat va copy ustida qiymatni o‘zgartir.

In [ ]:
import numpy as np

# Create an array with 6 elements
original_array = np.arange(6)
print("Original array:", original_array)

# Reshape the array to (3, 2)
reshaped_array = original_array.reshape(3, 2)
print("Reshaped array (3, 2):\n", reshaped_array)
print("Shape of reshaped array:", reshaped_array.shape)

9-masala

Massiv yarat va uning shape ni (3, 2) ga o‘zgartir.

In [ ]:
import numpy as np

# Create an array with 6 elements
original_array = np.arange(6)
print("Original array:", original_array)

# Reshape the array to (3, 2)
reshaped_array = original_array.reshape(3, 2)
print("Reshaped array (3, 2):\n", reshaped_array)
print("Shape of reshaped array:", reshaped_array.shape)

10-masala

np.arange(12) massivini 3 o‘lchamli shaklga (2x2x3) o‘zgartir.

In [ ]:
import numpy as np

arr = np.arange(12)
print("Original 1D array:", arr)

arr_3d = arr.reshape(2, 2, 3)
print("Reshaped 3D array (2x2x3):\n", arr_3d)
print("Shape of 3D array:", arr_3d.shape)

11-masala

Massivning shape ni o‘zgartirmasdan uning nusxasini (copy) yarat.

In [ ]:
import numpy as np

original_arr = np.array([[1, 2], [3, 4]])
print("Original array:\n", original_arr)
print("Shape of original array:", original_arr.shape)

# Create a copy without changing shape
copied_arr = original_arr.copy()
print("\nCopied array:\n", copied_arr)
print("Shape of copied array:", copied_arr.shape)

# Verify that they are different objects but have the same shape
print("\nAre they the same object?", original_arr is copied_arr)
print("Do they have the same shape?", original_arr.shape == copied_arr.shape)

12-masala

np.ones((2,3)) massivining shape ni chiqar.

In [ ]:
import numpy as np
arr = np.ones((2, 3))
print(arr)
print(arr.shape)

13-masala

Massivni (6,) shaklidan (2,3) shaklga o‘tkaz.

In [ ]:
import numpy as np

# Create a 1D array with shape (6,)
original_array = np.arange(6) # This creates [0, 1, 2, 3, 4, 5]
print("Original array (shape ", original_array.shape, "):")
print(original_array)

# Reshape the array to (2,3)
reshaped_array = original_array.reshape(2, 3)
print("\nReshaped array (shape ", reshaped_array.shape, "):")
print(reshaped_array)

14-masala

reshape(-1, 2) yordamida massivni qayta shakllantir.

15-masala

Massivdan copy ol va ikkala massivni solishtir (== bilan).

# dasr_3

1 dan 10 gacha bo‘lgan tasodifiy bitta sonni chiqaruvchi dastur yozing.

In [ ]:
son1 = random.randint(1, 10)
son1

4

5 ta elementdan iborat, 0 dan 50 gacha tasodifiy sonlardan iborat massiv yarating.

In [ ]:
import numpy as np

random_array = np.random.randint(0, 51, size=5)
print(random_array)

[28 42 20 10  0]


10 ta tasodifiy son (1–100 oralig‘ida) hosil qiling va ularning yig‘indisini toping.

In [ ]:
import numpy as np
sonlar1 = np.random.randint(1, 101, size=10)
sonlar2 = sonlar1.sum()

print("Tasodifiy sonlar:", sonlar1)
print("Raqamlar yig'indisi:", sonlar2)

Tasodifiy sonlar: [98 39 63 31 54 88 33  5 55 43]
Raqamlar yig'indisi: 509


3x3 o‘lchamli matritsa yarating (elementlari 0–9 oralig‘ida bo‘lsin).

In [ ]:
import numpy as np

sonlar_3x3 = np.random.randint(0, 10, size=(3, 3))
print(sonlar_3x3)

[[8 4 0]
 [8 0 7]
 [8 3 3]]


20 ta tasodifiy son ichidan faqat juft sonlarni ajratib chiqaring.

In [ ]:
import numpy as np
kop_sonlar = np.random.randint(1, 101, size=20)
Juft_sonlar = random_numbers[random_numbers % 2 == 0]

print("Tasodifiy sonlar:", kop_sonlar)
print("Sonlar yig'indisi:", Juft_sonlar)

Tasodifiy sonlar: [17 25 10 49 77 37 74 69  8  4 41 37 95 33 56 81 47 71 98 17]
Sonlar yig'indisi: [48 14 82 94 64 58 54  6 62]


0 va 1 oralig‘ida bitta tasodifiy haqiqiy son chiqaring.

In [ ]:
import numpy as np

random_float = np.random.rant()
print(random_float)

AttributeError: module 'numpy.random' has no attribute 'rant'